# Site settings
title: meditations.log.1
email: email [at] example.com
description: "A collection of thoughts on software development, improvisational comedy and New York life"
baseurl: ""
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: pretty
highlight: pygments
